Determine the principle stresses and directions for the following stress tensors:

 a. $$\mathbf{S} = \begin{bmatrix} 18 & 0 & 24 \\ 0 & -50 & 0 \\ 24 & 0 & 32 \end{bmatrix}$$
 
 b. $$\mathbf{S} = \begin{bmatrix} 3 & -10 & 0 \\ -10 & 0 & 30 \\ 0 & 30 & -27 \end{bmatrix}$$
 
 c. $$\mathbf{S} = \begin{bmatrix} 2 & -1 & 1 \\ -1 & 0 & 1 \\ 1 & 1 & -2 \end{bmatrix}$$
 
 Work (a) by hand for practice.  You can use a computer to solve (b) and (c) if you wish.
 
 **Solution:**

In [1]:
import numpy as np

values, vectors = np.linalg.eig(np.array([[18,0,24],[0, -50, 0],[24, 0, 32]]))

print("Eigenvalues: \n", np.real(values))
print("Eigenvectors: \n", vectors)

Eigenvalues: 
 [  0.  50. -50.]
Eigenvectors: 
 [[-0.8 -0.6  0. ]
 [ 0.   0.   1. ]
 [ 0.6 -0.8  0. ]]


In [2]:
values, vectors = np.linalg.eig(np.array([[3,-10,0],[-10, 0, 30],[0, 30, -27]]))

print("Eigenvalues: \n", np.real(values))
print("Eigenvectors: \n", vectors)

Eigenvalues: 
 [ 2.30000000e+01  2.66453526e-15 -4.70000000e+01]
Eigenvectors: 
 [[ 0.3940552   0.9124486  -0.11026357]
 [-0.78811041  0.27373458 -0.55131785]
 [-0.47286624  0.30414953  0.82697677]]


In [3]:
values, vectors = np.linalg.eig(np.array([[2,-1,1],[-1, 0, 1],[1, 1, -2]]))

print("Eigenvalues: \n", np.real(values))
print("Eigenvectors: \n", vectors)

Eigenvalues: 
 [-2.77845712  2.48928857  0.28916855]
Eigenvectors: 
 [[ 0.26826216  0.93698901  0.22380127]
 [ 0.41025777 -0.32131516  0.85348997]
 [-0.87162146  0.13714285  0.47060372]]
